name: RSS to Email

on:
  schedule:
    # Run daily at 5:00 AM UTC (equivalent to original cron: 0 5 * * *)
    - cron: '0 5 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  process-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Check RSS duration
        run: |
          python scripts/rss_duration.py --log-level INFO

      - name: Process feeds and send emails
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: 587
        run: |
          python process_feeds.py
